# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - {
                    name: "styles",
                    items:
                    [
                        "Bold",
                        "Italic",
                        "Underline",
                        "Strike",
                        "Blockquote",
                        "-",
                        "Link",
                        "-",
                        "RemoveFormat",
                        "-",
                        "NumberedList",
                        "BulletedList",
                        "-",
                        "Outdent",
                        "Indent",
                        "-",
                        "-",
                        "JustifyLeft",
                        "JustiftCenter",
                        "JustifyRight",
                        "JustifyBlock",
                        "-",
                        "-",
                        "-",
                        "-",
                        "Styles",
                        "Format",
                        "Font",
                        "FontSize",
                        "-",
                        'TextColor',
                        "BGColor",
                        "Sources",
                    ],
                }
